public class LibroConAutor{
    public int IdLibro{get;set;}
    public string Nombre{get;set;}
    public string Tapa{get;set;}
    public string ContraTapa{get;set;}
    public string Genero1Nombre{get;set;}
    public string Genero2Nombre{get;set;}
    public string Genero3Nombre{get;set;}
    public string Genero4Nombre{get;set;}
    public string Genero5Nombre{get;set;}
    public string NombreEscritor{get;set;}
    public string BioEscritor{get;set;}
    public string FotoEscritor{get;set;}
    public DateTime AnoPublicacion{get;set;}
    public string Sinopsis{get;set;}
    public int Reseña1{get;set;}
    public int Reseña2{get;set;}
    public int Reseña3{get;set;}
    public int Reseña4{get;set;}
    public int Reseña5{get;set;}
    public int ReseñasTotales{get;set;}
    public double promedioPuntuacion{get;set;}
}